- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: todo-app-denish
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: todo-app-denish
    template:
      metadata:
        labels:
          app: todo-app-denish
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: todo-app-denish
            image: denishjackson/todo-app-denish:latest
            ports:
              - containerPort: 3000
- apiVersion: v1
  kind: Service
  metadata:
    name: todo-app-denish-service
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 3000
        name: port3000
        port: 3000
        protocol: TCP
    selector:
      app: todo-app-denish